# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_tipo_empresa = QtWidgets.QComboBox(self.centralwidget)
        self.combo_tipo_empresa.setGeometry(QtCore.QRect(540, 70, 241, 23))
        self.combo_tipo_empresa.setCurrentText("")
        self.combo_tipo_empresa.setObjectName("combo_tipo_empresa")
        self.label_empresa = QtWidgets.QLabel(self.centralwidget)
        self.label_empresa.setGeometry(QtCore.QRect(10, 40, 161, 21))
        self.label_empresa.setObjectName("label_empresa")
        self.label_cuit = QtWidgets.QLabel(self.centralwidget)
        self.label_cuit.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_cuit.setObjectName("label_cuit")
        self.label_tipo_empresa = QtWidgets.QLabel(self.centralwidget)
        self.label_tipo_empresa.setGeometry(QtCore.QRect(410, 70, 121, 21))
        self.label_tipo_empresa.setObjectName("label_tipo_empresa")
        self.input_nombre_empresa = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nombre_empresa.setGeometry(QtCore.QRect(210, 40, 571, 23))
        self.input_nombre_empresa.setObjectName("input_nombre_empresa")
        self.input_cuit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cuit.setGeometry(QtCore.QRect(210, 70, 191, 23))
        self.input_cuit.setObjectName("input_cuit")
        self.combo_actividades = QtWidgets.QComboBox(self.centralwidget)
        self.combo_actividades.setGeometry(QtCore.QRect(210, 100, 571, 23))
        self.combo_actividades.setCurrentText("")
        self.combo_actividades.setObjectName("combo_actividades")
        self.label_actividad = QtWidgets.QLabel(self.centralwidget)
        self.label_actividad.setGeometry(QtCore.QRect(10, 100, 201, 16))
        self.label_actividad.setObjectName("label_actividad")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 10, 271, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 132, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 62, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 174, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 132, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 62, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 174, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 172, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 132, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 62, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 46, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 93, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.tab_requisitos = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_requisitos.setGeometry(QtCore.QRect(0, 130, 851, 421))
        self.tab_requisitos.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_requisitos.setObjectName("tab_requisitos")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.frame = QtWidgets.QFrame(self.tab_general)
        self.frame.setGeometry(QtCore.QRect(20, 20, 801, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(280, 10, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_requisito_1 = QtWidgets.QLabel(self.frame)
        self.label_requisito_1.setGeometry(QtCore.QRect(10, 50, 721, 16))
        self.label_requisito_1.setObjectName("label_requisito_1")
        self.porcentaje_asignado = QtWidgets.QLabel(self.frame)
        self.porcentaje_asignado.setGeometry(QtCore.QRect(640, 80, 101, 21))
        self.porcentaje_asignado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.porcentaje_asignado.setObjectName("porcentaje_asignado")
        self.input_facturacion = QtWidgets.QLineEdit(self.frame)
        self.input_facturacion.setGeometry(QtCore.QRect(172, 80, 141, 23))
        self.input_facturacion.setObjectName("input_facturacion")
        self.label_facturacion_anual = QtWidgets.QLabel(self.frame)
        self.label_facturacion_anual.setGeometry(QtCore.QRect(10, 80, 181, 21))
        self.label_facturacion_anual.setObjectName("label_facturacion_anual")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(332, 80, 161, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(512, 80, 131, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radio_no_presenta = QtWidgets.QRadioButton(self.frame)
        self.radio_no_presenta.setGeometry(QtCore.QRect(420, 190, 311, 21))
        self.radio_no_presenta.setChecked(True)
        self.radio_no_presenta.setObjectName("radio_no_presenta")
        self.radio_presenta = QtWidgets.QRadioButton(self.frame)
        self.radio_presenta.setGeometry(QtCore.QRect(30, 190, 291, 21))
        self.radio_presenta.setObjectName("radio_presenta")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 751, 41))
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 801, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 110, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tab_requisitos.addTab(self.tab_general, "")
        self.tab_especifico = QtWidgets.QWidget()
        self.tab_especifico.setObjectName("tab_especifico")
        self.frame_2 = QtWidgets.QFrame(self.tab_especifico)
        self.frame_2.setGeometry(QtCore.QRect(7, 10, 831, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(610, 20, 191, 23))
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 761, 51))
        self.label_6.setObjectName("label_6")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(40, 120, 491, 21))
        self.checkBox.setObjectName("checkBox")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(480, 120, 131, 41))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(610, 130, 191, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(610, 190, 191, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 451, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(480, 180, 131, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(0, 160, 831, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(0, 60, 831, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(0, 230, 831, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 761, 71))
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(610, 260, 191, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(480, 250, 131, 41))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(330, 320, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.tab_requisitos.addTab(self.tab_especifico, "")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 381, 16))
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_requisitos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CHECK LIST"))
        self.label_empresa.setText(_translate("MainWindow", "Nombre de la empresa"))
        self.label_cuit.setText(_translate("MainWindow", "CUIT"))
        self.label_tipo_empresa.setText(_translate("MainWindow", "Tipo de empresa"))
        self.label_actividad.setText(_translate("MainWindow", "Actividad Promovida (Art. 2)"))
        self.label_4.setText(_translate("MainWindow", "FORMA DE REVISIÓN # 1"))
        self.label.setText(_translate("MainWindow", "REQUISITOS GENERALES"))
        self.label_requisito_1.setText(_translate("MainWindow", "1.- Artículo 4-a:  70% de la facturación total del último año generada a partir de actividades promovidas."))
        self.porcentaje_asignado.setText(_translate("MainWindow", "%"))
        self.label_facturacion_anual.setText(_translate("MainWindow", "Facturación anual (AR$)"))
        self.label_3.setText(_translate("MainWindow", "Monto designado (AR$)"))
        self.radio_no_presenta.setText(_translate("MainWindow", "No presenta documentación respaldatoria."))
        self.radio_presenta.setText(_translate("MainWindow", "Presenta documentación respaldatoria."))
        self.label_2.setText(_translate("MainWindow", "2.- Artículo 4-b:  Acreditación del desarrollo de actividades promovidas de manera intensiva para incorporar\n"
" conocimiento."))
        self.pushButton_2.setText(_translate("MainWindow", "verificar"))
        self.tab_requisitos.setTabText(self.tab_requisitos.indexOf(self.tab_general), _translate("MainWindow", "Requisitos Generales"))
        self.label_5.setText(_translate("MainWindow", "3.- Artículo 4-b_1: Acredita la realización de mejoras continuas en la calidad de sus \n"
"servicios, productos y/o procesos, o mediante una norma de calidad reconocida aplicable\n"
" a sus servicios, productos y/o procesos."))
        self.label_6.setText(_translate("MainWindow", "4.- Artículo 4-b/2-a:  Acreditar capacitación de sus empleados y/o destinatarios en general en temáticas relacionadas con \n"
"la economía del  conocimiento en un porcentaje respecto de su masa salarial del último año."))
        self.checkBox.setText(_translate("MainWindow", "Fue orientada a población que compute el doble del monto."))
        self.label_7.setText(_translate("MainWindow", "Monto \n"
"acreditado (AR$)"))
        self.label_8.setText(_translate("MainWindow", "5.- Artículo 4-b/2-b:  Investigación y desarrollo (que incluya \n"
"novedad, originalidad y/o creatividad) en un porcentaje \n"
"respecto de su facturación total del último año."))
        self.label_9.setText(_translate("MainWindow", "Monto \n"
"acreditado (AR$)"))
        self.label_10.setText(_translate("MainWindow", "6.- Acreditar la realización de exportaciones de bienes y/o servicios que\n"
"surjan del desarrollo de alguna de las actividades promovidas y/o del\n"
"desarrollo y aplicación intensiva de las mismas en un porcentaje\n"
"respecto de su facturación total del último año."))
        self.label_11.setText(_translate("MainWindow", "Monto \n"
"acreditado (AR$)"))
        self.pushButton.setText(_translate("MainWindow", "Ver resultado"))
        self.tab_requisitos.setTabText(self.tab_requisitos.indexOf(self.tab_especifico), _translate("MainWindow", "Requisitos Especificos"))
        self.label_13.setText(_translate("MainWindow", "Dirección de Estrategias de Economía del Conocimiento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
